# Generated by Django 2.2 on 2020-02-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateTimeField(default='1960-01-01'),
            preserve_default=False,
        ),
    ]
